version: "3.7"

x-build-client-env: &build-client-env
  PLACEOS_BUILD_HOST: ${PLACEOS_BUILD_HOST:-build}
  PLACEOS_BUILD_PORT: ${PLACEOS_BUILD_PORT:-3000}

services:
  # Driver test harness
  drivers:
    image: placeos/drivers-spec:crystal-${CRYSTAL_VERSION:-1.1.1}
    restart: always
    container_name: placeos-drivers
    hostname: drivers
    depends_on:
      - build
      - redis
      - install-shards
    ports:
      - 127.0.0.1:8085:8080
      - 127.0.0.1:4444:4444
    volumes:
      - ./.git:/app/.git
      - ./.logs:/app/report_failures
      - ./drivers:/app/drivers
      - ./lib:/app/lib
      - ./src:/app/src
      - ./repositories:/app/repositories
    environment:
      <<: *build-client-env
      CI: ${CI:-}
      CRYSTAL_PATH: lib:/lib/local-shards
      REDIS_URL: redis://redis:6379
      TZ: $TZ

  build:
    image: placeos/build:${PLACE_BUILD_TAG:-nightly}
    restart: always
    hostname: build
    environment:
      <<: *deployment-env
      AWS_KEY: ${AWS_KEY}
      AWS_SECRET: ${AWS_SECRET}
      AWS_REGION: ${AWS_REGION:-p-southeast-2}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET:-arn:aws:s3:::placeos-drivers}
      TZ: $TZ

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
    environment:
      TZ: $TZ

  # Ensures shards are installed.
  install-shards:
    image: crystallang/crystal:${CRYSTAL_VERSION:-1.1.1}-alpine
    restart: "no"
    working_dir: /wd
    command: ash -c 'shards check -q || shards install'
    environment:
      SHARDS_OPTS: "--ignore-crystal-version"
    volumes:
      - ./shard.lock:/wd/shard.lock
      - ./shard.yml:/wd/shard.yml
      - ./shard.override.yml:/wd/shard.override.yml
      - ./.shards:/wd/.shards
      - ./lib:/wd/lib
