name: Build
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2  # https://github.com/github/feedback/discussions/5251
      - name: Build Drivers
        run: |
          ./harness build \
            --discover \
            --strict-driver-info \
            --repository-uri https://github.com/${{ github.repository }} \
            --repository-path ./repositories/drivers \
            --branch $CI_ACTION_REF_NAME \
            --commit ${{ github.sha }}
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_SECRET: ${{ secrets.AWS_SECRET }}
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
